

show_font: show_font.c
	/work/arm_linux_gcc/gcc-linaro-4.9.4-2017.01-x86_64_armv8l-linux-gnueabihf/bin/armv8l-linux-gnueabihf-gcc -finput-charset=UTF-8 -fexec-charset=GBK -o show_font show_font.c
	
cp:
	sudo cp show_font /work/rootfs/x6818_rootfs_mini/test/ -f

clean:
	rm show_font




